### ISSUE TITLE
作者，你好，假死的bug能不能修修

### ISSUE THREAD

**Issue by ivkeji** [Zhaokugua/Bili_music_down#1]
多次以为，这个软件是不是挂了。不过真的没有挂，成功下载，谢谢作者

**Comment by Zhaokugua** [comment]
没想到真有人用😂
这代码写了好多年了我也忘的差不多了（
不过我记得好像假死是易语言的特性（
具体我也不太清楚怎么修
有空看看

**Comment by Zhaokugua** [comment]
V1.6 已修复
下载方式改为了系统自带的curl下载

**Comment by TheCGDF** [comment]
似乎仍未完全修复。
一开始先是尝试下载了一首发现可以下载后就关掉去睡觉了，过了一晚再打开后怎么试怎么不行，客户端自带的清缓存、客户端整个删除重下都试了下载还是卡在0%。
神奇的是换了同一网络环境的另一台电脑就可以了。
现在也不敢关了，怕关掉再打开就又不行了。。。

**Comment by Zhaokugua** [comment]
确实还有一部分问题，b站返回的某些cdn不会返回文件大小、MD5那些信息，我就不好判断文件是否已经下载完，确实有这个问题
不过暂时可以换个网络等几分钟重下，他应该会重新获取CDN链接，大部分CDN链接还是有文件大小信息的

**Comment by Zhaokugua** [comment]
确实还有一部分问题，b站返回的某些cdn不会返回文件大小、MD5那些信息，我就不好判断文件是否已经下载完，确实有这个问题
不过暂时可以换个网络等几分钟重下，他应该会重新获取CDN链接，大部分CDN链接还是有文件大小信息的
